
env:
  AZURE_WEBAPP_NAME: assignment-webapp
  AZURE_WEBAPP_PACKAGE_PATH: 'Front-End/recap-project'
  ACR_NAME: assignmentacr1
  ACR_USERNAME: assignmentacr1
  ACR_PASSWORD: 8K4IpVo2ub339zv6olPNuX5VCE6EKeO9+8uBHT2/M++ACRCCTiUF

on:
  push:
    paths: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    branches:
      - main

permissions:
  contents: 'read'
  packages: 'write'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        
      - name: Log in to Azure Container Registry
        run: |
          docker login -u ${{ env.ACR_USERNAME }} -p ${{ env.ACR_PASSWORD }} assignmentacr1.azurecr.io

      - name: Build and push container image to Azure Container Registry
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/frontend:${{ github.sha }} -f ./Dockerfile .
          docker push ${{ env.ACR_NAME }}.azurecr.io/frontend:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest

    needs: build

    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:


      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_FRONTEND_PUBLISH_PROFILE}}
          images: '${{ env.ACR_NAME }}.azurecr.io/${{ env.REPO }}:${{ github.sha }}'
